# Generated by Django 5.0.3 on 2024-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
